import { UserProfile, Disciplina, Aula, Avaliacao, Material } from '@/types';

export const mockUsers: UserProfile[] = [
  {
    id: 'u-aluno-1',
    email: 'aluno@uicb.edu.br',
    full_name: 'João Silva (Aluno)',
    role: 'aluno',
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'u-prof-1',
    email: 'hilario@uicb.edu.br',
    full_name: 'Profº Hilário Bispo',
    role: 'professor',
    avatar_url: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'u-prof-2',
    email: 'cleiton@uicb.edu.br',
    full_name: 'Profº Cleiton Barbirato',
    role: 'professor',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'u-monitor-1',
    email: 'camila@uicb.edu.br',
    full_name: 'Camila (Monitora)',
    role: 'monitor',
    avatar_url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'u-admin-1',
    email: 'admin@uicb.edu.br',
    full_name: 'Pr. Carlos Santos (Admin)',
    role: 'admin',
    avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
  },
];

export const mockDisciplinas: Disciplina[] = [
  // TURMA A (7º Período - Semanal Noturno - Ordem Semanal do Google Drive & Agenda)
  {
    id: 'disc-1',
    code: 'HIS-202',
    name: '01 - História do Congregacionalismo - Ary Júnior',
    description: '16 encontros em 2 unidades temáticas (Mundial e Brasileira). Câmeras ligadas. Avaliação (10 pts): Prova escrita de unidade (0-8 pts) + Frequência ativa (1 pt) + Leitura obrigatória ética (1 pt).',
    professor_id: 'u-prof-ary',
    professor_name: 'Profº Ary Júnior',
    professor_email: 'queiroz.aryjr@gmail.com',
    monitor_id: 'u-monitor-1',
    monitor_name: 'Camila',
    day_of_week: 'Terça-feira',
    start_time: '19:00',
    end_time: '20:25',
    timezone: 'America/Sao_Paulo',
    semester: '2026.2',
    turma_id: 'turma-a',
    turma_idx: 1,
    google_meet_url: 'https://meet.google.com/sef-ggpp-bbn',
    google_meet_phone: '(BR) +55 19 4560-9588',
    google_meet_pin: '812 860 450#',
    google_drive_url: 'https://drive.google.com/open?id=19Y8Nv2Yvx1V-m4E5y5fUWOo5e8DZzeji&usp=drive_copy',
    attendance_form_url: 'https://forms.gle/2X7xGqge3dqdRKrGA',
  },
  {
    id: 'disc-2',
    code: 'HIS-102',
    name: '02 - História do Pensamento Cristão II - Hilário Bispo',
    description: 'Iluminismo e Modernidade (razão vs revelação). AV1: Pesquisa ABNT (individual ou até 3 alunos). AV2: Prova objetiva 10 questões no Google Forms. AV3: Exame oral temático.',
    professor_id: 'u-prof-hilario',
    professor_name: 'Profº Hilário Bispo',
    professor_email: 'hilario.graca@catolica.edu.br',
    monitor_id: 'u-monitor-1',
    monitor_name: 'Cristiano',
    day_of_week: 'Terça-feira',
    start_time: '20:35',
    end_time: '22:00',
    timezone: 'America/Sao_Paulo',
    semester: '2026.2',
    turma_id: 'turma-a',
    turma_idx: 1,
    google_meet_url: 'https://meet.google.com/cxj-yetd-xpf',
    google_meet_phone: '(BR) +55 11 4933-5763',
    google_meet_pin: '788 555 787#',
    google_drive_url: 'https://drive.google.com/open?id=1iKwbRf-oLpyphrFnM-Km5TWOo2UCU1Me&usp=drive_copy',
    attendance_form_url: 'https://forms.gle/hM2j2fb7DK923wdR7',
  },
  {
    id: 'disc-3',
    code: 'ACO-202',
    name: '03 - Aconselhamento Bíblico II - Uilian Santos',
    description: 'Avaliação exclusiva por 2 provas objetivas Google Forms baseadas nos slides (sem trabalhos escritos). Leitura obrigatória: "Ego Transformado" (Keller). Lista de presença ao final de cada aula.',
    professor_id: 'u-prof-uilian',
    professor_name: 'Profº Uilian Santos',
    professor_email: 'santosuilian093@gmail.com',
    monitor_id: 'u-monitor-1',
    monitor_name: 'Rosiane',
    day_of_week: 'Quarta-feira',
    start_time: '19:00',
    end_time: '20:25',
    timezone: 'America/Sao_Paulo',
    semester: '2026.2',
    turma_id: 'turma-a',
    turma_idx: 1,
    google_meet_url: 'https://meet.google.com/ifv-zsdd-gjx',
    google_meet_phone: '(BR) +55 11 4949-4189',
    google_meet_pin: '287 717 439#',
    google_drive_url: 'https://drive.google.com/open?id=1BUr0R4pLQjTt01ID8XjYKIBlZhAtaWcx&usp=drive_copy',
    attendance_form_url: 'https://forms.gle/iSLGtjyaTnM9tFGb6',
  },
  {
    id: 'disc-4',
    code: 'DIR-101',
    name: '04 - Direitos Humanos - Cleiton Barbirato',
    description: 'V1 e V2 compostas por Prova objetiva Forms (peso 8, sem consulta) + Trabalho de pesquisa escrito individual (peso 2). Média de aprovação >= 7. Textos e slides gratuitos na pasta.',
    professor_id: 'u-prof-cleiton',
    professor_name: 'Profº Cleiton Barbirato',
    professor_email: 'cleitonpb@gmail.com',
    monitor_id: 'u-monitor-1',
    monitor_name: 'Cristiano',
    day_of_week: 'Quarta-feira',
    start_time: '20:35',
    end_time: '22:00',
    timezone: 'America/Sao_Paulo',
    semester: '2026.2',
    turma_id: 'turma-a',
    turma_idx: 1,
    google_meet_url: 'https://meet.google.com/uva-zmav-rds',
    google_meet_phone: '(BR) +55 51 4560-7412',
    google_meet_pin: '670 189 539#',
    google_drive_url: 'https://drive.google.com/open?id=1fPSmFUBNzrzK--n3NDKOdMR5HWk25AV7&usp=drive_copy',
    attendance_form_url: 'https://forms.gle/QiWRgTit6XjxP9Ci7',
  },
  {
    id: 'disc-5',
    code: 'ETC-201',
    name: '05 - Ética Cristã - Karoline Evangelista',
    description: 'Livro-texto: Norman Geisler. Avaliação unificada V1/V2: Seminários práticos em grupos (3 a 4 alunos) sobre os Dez Mandamentos e Catecismo Maior de Westminster (22/10 a 19/11, 30 min, 10 min por orador). Nota individual.',
    professor_id: 'u-prof-karol',
    professor_name: 'Profª Karoline Evangelista',
    professor_email: 'karolteologia@gmail.com',
    monitor_id: 'u-monitor-1',
    monitor_name: 'Rosiane',
    day_of_week: 'Quinta-feira',
    start_time: '19:00',
    end_time: '20:25',
    timezone: 'America/Sao_Paulo',
    semester: '2026.2',
    turma_id: 'turma-a',
    turma_idx: 1,
    google_meet_url: 'https://meet.google.com/ypd-yzwg-nrw',
    google_meet_phone: '(BR) +55 31 3958-9560',
    google_meet_pin: '341 510 949#',
    google_drive_url: 'https://drive.google.com/open?id=1xuOm61ul94H3kdU5psFtbl-I2KZ41QJC&usp=drive_copy',
    attendance_form_url: 'https://forms.gle/Tn3Ln3iS9cbAUEsJ8',
  },
  {
    id: 'disc-6',
    code: 'NT-301',
    name: '06 - Novo Testamento III - Epístolas Gerais - Marcio Leal',
    description: 'Metodologia com câmeras ligadas e anotações ativas dos slides sintéticos. Livro-base: Introdução ao NT (Carson/Moo/Morris). Avaliação: Carga massiva de 150 questões discursivas e orais no Forms.',
    professor_id: 'u-prof-marcio',
    professor_name: 'Profº Marcio Leal',
    professor_email: 'pr.marcioleal@gmail.com',
    monitor_id: 'u-monitor-1',
    monitor_name: 'Camila',
    day_of_week: 'Quinta-feira',
    start_time: '20:35',
    end_time: '22:00',
    timezone: 'America/Sao_Paulo',
    semester: '2026.2',
    turma_id: 'turma-a',
    turma_idx: 1,
    google_meet_url: 'https://meet.google.com/nyn-xjqk-vky',
    google_meet_phone: '(BR) +55 11 4935-0167',
    google_meet_pin: '813 789 014#',
    google_drive_url: 'https://drive.google.com/open?id=1ppsv5caJVbHw-1RwhHu8nxBmqFT9Wm9P&usp=drive_copy',
    attendance_form_url: 'https://forms.gle/SC1mSMSZfDhJPPVE9',
  },
  {
    id: 'disc-7',
    code: 'MIS-202',
    name: '07 - Plantação e Revitalização de Igrejas II - Thácyto Lessa',
    description: 'Foco em Revitalização de Igrejas. Câmeras ligadas. AV1: Resumo capítulo por capítulo (1 página por cap., 12 folhas) de "A Treliça e a Videira" (entrega até 27/11). AV2: Prova com consulta em 27/11.',
    professor_id: 'u-prof-thacyto',
    professor_name: 'Profº Thácyto Lessa',
    professor_email: 'thacyto@gmail.com',
    monitor_id: 'u-monitor-1',
    monitor_name: 'Camila',
    day_of_week: 'Sexta-feira',
    start_time: '19:00',
    end_time: '20:00',
    timezone: 'America/Sao_Paulo',
    semester: '2026.2',
    turma_id: 'turma-a',
    turma_idx: 1,
    google_meet_url: 'https://meet.google.com/jwb-wpvc-pzm',
    google_meet_phone: '(BR) +55 11 4935-2549',
    google_meet_pin: '177 432 157#',
    google_drive_url: 'https://drive.google.com/open?id=1nzXIDnWvvrxSgXQULaSvDGdVr32L_xP8&usp=drive_copy',
    attendance_form_url: 'https://forms.gle/bSqjHe7zsV1EJDDB6',
  },
  {
    id: 'disc-8',
    code: 'TCC-101',
    name: '08 - TCC I - Gabriela Leal',
    description: 'Grupo WhatsApp: TCC1 2026.2. Prazo do projeto: 2 semanas a contar de 21/08 (04/09). Estrutura ABNT: Capa, Sumário, Objetivos, Justificativa, Referencial, Cronograma. Linguagem impessoal. Orientador por afinidade.',
    professor_id: 'u-prof-gabriela',
    professor_name: 'Profª Gabriela Leal',
    professor_email: 'gabriela.lealg7757@gmail.com',
    monitor_id: 'u-monitor-1',
    monitor_name: 'Rosiane',
    day_of_week: 'Sexta-feira',
    start_time: '20:00',
    end_time: '21:00',
    timezone: 'America/Sao_Paulo',
    semester: '2026.2',
    turma_id: 'turma-a',
    turma_idx: 1,
    google_meet_url: 'https://meet.google.com/jnz-hkqd-edc',
    google_meet_phone: '(BR) +55 11 4935-6584',
    google_meet_pin: '568 309 440#',
    google_drive_url: 'https://drive.google.com/open?id=1f-9i-TpqaZhzoLyrxg6flM6CHTsAOWPj&usp=drive_copy',
    attendance_form_url: 'https://forms.gle/vULryGYArnJZgBF28',
  },
  {
    id: 'disc-9',
    code: 'AFR-101',
    name: '09 - História da Cultura Afro Brasileira e Indígena - Emerson Silva',
    description: 'Estudo da formação étnica brasileira, diversidade cultural e aplicação pastoral.',
    professor_id: 'u-prof-emerson',
    professor_name: 'Profº Emerson Silva',
    professor_email: 'emerson@uicb.edu.br',
    monitor_id: 'u-monitor-cristiano',
    monitor_name: 'Cristiano',
    day_of_week: 'Sexta-feira',
    start_time: '21:00',
    end_time: '22:00',
    timezone: 'America/Sao_Paulo',
    semester: '2026.2',
    turma_id: 'turma-a',
    turma_idx: 1,
    google_meet_url: 'https://meet.google.com/jnz-hkqd-edc',
    google_meet_phone: '(BR) +55 11 4935-6584',
    google_meet_pin: '568 309 440#',
    google_drive_url: 'https://drive.google.com/open?id=13vp8jOcvdtH13O2iauyvsaTCw7DwiPIa&usp=drive_copy',
    attendance_form_url: 'https://forms.gle/vULryGYArnJZgBF28',
  },

  // TURMA B (3º Período - Semanal Noturno)
  {
    id: 'disc-b-1',
    code: 'INT-101',
    name: 'Introdução ao Novo Testamento',
    description: 'Estudo histórico, eclesiológico e literário dos evangelhos e contexto do Novo Testamento.',
    professor_id: 'u-prof-leo',
    professor_name: 'Profº Leonardo Paulino',
    professor_email: 'leonardo@uicb.edu.br',
    monitor_id: 'u-monitor-1',
    monitor_name: 'Monitoria Turma B',
    day_of_week: 'Terça-feira',
    start_time: '19:00',
    end_time: '20:25',
    timezone: 'America/Sao_Paulo',
    semester: '2026.2',
    turma_id: 'turma-b',
    turma_idx: 2,
    google_meet_url: 'https://meet.google.com/esq-sjmd-sau',
    google_meet_phone: '(BR) +55 11 4933-7995',
    google_meet_pin: '930 167 860#',
    google_meet_tel_url: 'https://tel.meet/esq-sjmd-sau?pin=6781630980308',
    google_drive_url: 'https://drive.google.com/open?id=1jQ0co8yOr0shnKxVX_lv2JTAM8AQNCMO',
  },
  {
    id: 'disc-b-2',
    code: 'HER-101',
    name: 'Hermenêutica Bíblica',
    description: 'Princípios e métodos de interpretação das Escrituras, exegese e aplicação teológica.',
    professor_id: 'u-prof-david',
    professor_name: 'Profº David Bezerra',
    professor_email: 'david@uicb.edu.br',
    monitor_id: 'u-monitor-1',
    monitor_name: 'Monitoria Turma B',
    day_of_week: 'Terça-feira',
    start_time: '20:35',
    end_time: '22:00',
    timezone: 'America/Sao_Paulo',
    semester: '2026.2',
    turma_id: 'turma-b',
    turma_idx: 2,
    google_meet_url: 'https://meet.google.com/vee-maaz-cdn',
    google_meet_phone: '(BR) +55 51 4560-7523',
    google_meet_pin: '800 017 642#',
    google_meet_tel_url: 'https://tel.meet/vee-maaz-cdn?pin=2110831424383',
    google_drive_url: 'https://drive.google.com/open?id=1jQ0co8yOr0shnKxVX_lv2JTAM8AQNCMO',
  },
  {
    id: 'disc-b-3',
    code: 'DIS-101',
    name: 'Fundamentos e Prática do Discipulado',
    description: 'Formação espiritual, acompanhamento pastoral e processos práticos de discipulado na igreja.',
    professor_id: 'u-prof-milton',
    professor_name: 'Profº José Milton',
    professor_email: 'josemilton@uicb.edu.br',
    monitor_id: 'u-monitor-1',
    monitor_name: 'Monitoria Turma B',
    day_of_week: 'Quarta-feira',
    start_time: '19:00',
    end_time: '20:25',
    timezone: 'America/Sao_Paulo',
    semester: '2026.2',
    turma_id: 'turma-b',
    turma_idx: 2,
    google_meet_url: 'https://meet.google.com/xrk-hfza-tks',
    google_meet_phone: '(BR) +55 21 4560-7221',
    google_meet_pin: '221 096 667#',
    google_meet_tel_url: 'https://tel.meet/xrk-hfza-tks?pin=7368054294151',
    google_drive_url: 'https://drive.google.com/open?id=1jQ0co8yOr0shnKxVX_lv2JTAM8AQNCMO',
  },
  {
    id: 'disc-b-4',
    code: 'MIS-101',
    name: 'Teologia da Missão',
    description: 'Perspectivas bíblicas, históricas e estratégicas da missão da igreja local no mundo.',
    professor_id: 'u-prof-jefferson',
    professor_name: 'Profº Jefferson Pontes',
    professor_email: 'jefferson@uicb.edu.br',
    monitor_id: 'u-monitor-1',
    monitor_name: 'Monitoria Turma B',
    day_of_week: 'Quarta-feira',
    start_time: '20:35',
    end_time: '22:00',
    timezone: 'America/Sao_Paulo',
    semester: '2026.2',
    turma_id: 'turma-b',
    turma_idx: 2,
    google_meet_url: 'https://meet.google.com/gjg-jrbq-atk',
    google_meet_phone: '(BR) +55 41 4560-9980',
    google_meet_pin: '732 549 857#',
    google_meet_tel_url: 'https://tel.meet/gjg-jrbq-atk?pin=8301681074857',
    google_drive_url: 'https://drive.google.com/open?id=1jQ0co8yOr0shnKxVX_lv2JTAM8AQNCMO',
  },
  {
    id: 'disc-b-5',
    code: 'TS-301',
    name: 'Teologia Sistemática III - Cristologia/Pneumatologia',
    description: 'Doutrina da pessoa e obra do Senhor Jesus Cristo e da pessoa e obra do Espírito Santo.',
    professor_id: 'u-prof-marcio',
    professor_name: 'Profº Marcio Leal',
    professor_email: 'pr.marcioleal@gmail.com',
    monitor_id: 'u-monitor-1',
    monitor_name: 'Monitoria Turma B',
    day_of_week: 'Quinta-feira',
    start_time: '19:00',
    end_time: '20:25',
    timezone: 'America/Sao_Paulo',
    semester: '2026.2',
    turma_id: 'turma-b',
    turma_idx: 2,
    google_meet_url: '',
    google_drive_url: 'https://drive.google.com/open?id=1jQ0co8yOr0shnKxVX_lv2JTAM8AQNCMO',
  },
  {
    id: 'disc-b-6',
    code: 'AT-201',
    name: 'Antigo Testamento II - Livros Históricos',
    description: 'Análise literária, histórica e teológica dos livros históricos do cânon do Antigo Testamento.',
    professor_id: 'u-prof-betania',
    professor_name: 'Profª Betânia Barbosa',
    professor_email: 'betania@uicb.edu.br',
    monitor_id: 'u-monitor-1',
    monitor_name: 'Monitoria Turma B',
    day_of_week: 'Quinta-feira',
    start_time: '20:35',
    end_time: '22:00',
    timezone: 'America/Sao_Paulo',
    semester: '2026.2',
    turma_id: 'turma-b',
    turma_idx: 2,
    google_meet_url: '',
    google_drive_url: 'https://drive.google.com/open?id=1jQ0co8yOr0shnKxVX_lv2JTAM8AQNCMO',
  },
  {
    id: 'disc-b-7',
    code: 'MIS-202B',
    name: 'Plantação e Revitalização de Igrejas II',
    description: 'Estratégia missionária, plantação de novas comunidades e revitalização de igrejas.',
    professor_id: 'u-prof-thacyto',
    professor_name: 'Profº Thácyto Lessa',
    professor_email: 'thacyto@gmail.com',
    monitor_id: 'u-monitor-1',
    monitor_name: 'Camila',
    day_of_week: 'Sexta-feira',
    start_time: '19:00',
    end_time: '20:25',
    timezone: 'America/Sao_Paulo',
    semester: '2026.2',
    turma_id: 'turma-b',
    turma_idx: 2,
    google_meet_url: 'https://meet.google.com/jwb-wpvc-pzm',
    google_meet_phone: '(BR) +55 11 4935-2549',
    google_meet_pin: '177 432 157#',
    google_drive_url: 'https://drive.google.com/open?id=1nzXIDnWvvrxSgXQULaSvDGdVr32L_xP8&usp=drive_copy',
  },
  {
    id: 'disc-b-8',
    code: 'LID-101',
    name: 'Liderança Cristã',
    description: 'Princípios de liderança bíblica, desenvolvimento de equipes ministeriais e integridade cristã.',
    professor_id: 'u-prof-sandro',
    professor_name: 'Profº Sandro Cruz',
    professor_email: 'sandro@uicb.edu.br',
    monitor_id: 'u-monitor-1',
    monitor_name: 'Monitoria Turma B',
    day_of_week: 'Sexta-feira',
    start_time: '19:00',
    end_time: '20:25',
    timezone: 'America/Sao_Paulo',
    semester: '2026.2',
    turma_id: 'turma-b',
    turma_idx: 2,
    google_meet_url: '',
    google_drive_url: 'https://drive.google.com/open?id=1jQ0co8yOr0shnKxVX_lv2JTAM8AQNCMO',
  },
  {
    id: 'disc-b-9',
    code: 'HOM-101',
    name: 'Homilética I / Homilética II (Novatos26.2)',
    description: 'Elaboração e proclamação do sermão bíblico expositivo (Módulo Gravado).',
    professor_id: 'u-prof-wellington',
    professor_name: 'Profº Wellington Estrela',
    professor_email: 'wellington@uicb.edu.br',
    monitor_id: 'u-monitor-1',
    monitor_name: 'Módulo Gravado',
    day_of_week: 'Sexta-feira',
    start_time: '19:00',
    end_time: '21:00',
    timezone: 'America/Sao_Paulo',
    semester: '2026.2',
    turma_id: 'turma-b',
    turma_idx: 2,
    google_meet_url: '',
    google_meet_phone: '',
    google_meet_pin: '',
    google_drive_url: 'https://drive.google.com/open?id=1jQ0co8yOr0shnKxVX_lv2JTAM8AQNCMO',
  },
];

export const datasAvaliacoesMap: Record<string, { av1: string; av2: string }> = {
  // Turma A (Chaves completas com numeração do Drive e formato legado)
  '01 - História do Congregacionalismo - Ary Júnior': { av1: '29/09/2026', av2: '24/11/2026' },
  'História do Congregacionalismo': { av1: '29/09/2026', av2: '24/11/2026' },
  '02 - História do Pensamento Cristão II - Hilário Bispo': { av1: '29/09/2026', av2: '24/11/2026' },
  'História do Pensamento Cristão II': { av1: '29/09/2026', av2: '24/11/2026' },
  '03 - Aconselhamento Bíblico II - Uilian Santos': { av1: '30/09/2026', av2: '25/11/2026' },
  'Aconselhamento Bíblico II': { av1: '30/09/2026', av2: '25/11/2026' },
  '04 - Direitos Humanos - Cleiton Barbirato': { av1: '30/09/2026', av2: '25/11/2026' },
  'Direitos Humanos': { av1: '30/09/2026', av2: '25/11/2026' },
  '05 - Ética Cristã - Karoline Evangelista': { av1: '01/10/2026', av2: '26/11/2026' },
  'Ética Cristã': { av1: '01/10/2026', av2: '26/11/2026' },
  '06 - Novo Testamento III - Epístolas Gerais - Marcio Leal': { av1: '01/10/2026', av2: '26/11/2026' },
  'Novo Testamento III - Epístolas Gerais': { av1: '01/10/2026', av2: '26/11/2026' },
  '07 - Plantação e Revitalização de Igrejas II - Thácyto Lessa': { av1: '02/10/2026', av2: '27/11/2026' },
  'Plantação e Revitalização de Igrejas II': { av1: '02/10/2026', av2: '27/11/2026' },
  '08 - TCC I - Gabriela Leal': { av1: '02/10/2026', av2: '27/11/2026' },
  'TCC I': { av1: '02/10/2026', av2: '27/11/2026' },
  '09 - História da Cultura Afro Brasileira e Indígena - Emerson Silva': { av1: '02/10/2026', av2: '27/11/2026' },
  'História da Cultura Afro Brasileira e Indígena': { av1: '02/10/2026', av2: '27/11/2026' },

  // Turma B
  'Introdução ao Novo Testamento': { av1: '29/09/2026', av2: '24/11/2026' },
  'Hermenêutica Bíblica': { av1: '29/09/2026', av2: '24/11/2026' },
  'Fundamentos e Prática do Discipulado': { av1: '30/09/2026', av2: '25/11/2026' },
  'Teologia da Missão': { av1: '30/09/2026', av2: '25/11/2026' },
  'Teologia Sistemática III - Cristologia/Pneumatologia': { av1: '01/10/2026', av2: '26/11/2026' },
  'Antigo Testamento II - Livros Históricos': { av1: '01/10/2026', av2: '26/11/2026' },
  'Liderança Cristã': { av1: '02/10/2026', av2: '27/11/2026' },
  'Homilética I / Homilética II (Novatos26.2)': { av1: '02/10/2026', av2: '27/11/2026' },
  'Homilética I': { av1: '02/10/2026', av2: '27/11/2026' },
  'Homilética II': { av1: '02/10/2026', av2: '27/11/2026' },
};

export const mockAulas: Aula[] = [
  // ==========================================
  // TURMA A (7º Período - Semanal Noturno - Ordem Semanal do Google Drive & Agenda)
  // ==========================================
  {
    id: 'aula-20262-1',
    disciplina_id: 'disc-1',
    disciplina_name: '01 - História do Congregacionalismo - Ary Júnior',
    code: 'HIS-202',
    turma_id: 'turma-a',
    turma_idx: 1,
    professor_name: 'Profº Ary Júnior',
    monitor_name: 'Camila',
    day_of_week: 'Terça-feira',
    start_time: '19:00',
    end_time: '20:25',
    title: '01 • História do Congregacionalismo — Profº Ary Júnior',
    description: 'Origens históricas, legado teológico e expansão da denominação no Brasil.',
    scheduled_at: 'Terça-feira • 19:00 – 20:25',
    google_meet_url: 'https://meet.google.com/sef-ggpp-bbn',
    google_meet_phone: '(BR) +55 19 4560-9588',
    google_meet_pin: '812 860 450#',
    google_drive_url: 'https://drive.google.com/open?id=19Y8Nv2Yvx1V-m4E5y5fUWOo5e8DZzeji&usp=drive_copy',
    attendance_form_url: 'https://forms.gle/2X7xGqge3dqdRKrGA',
    ai_summary_url: 'https://docs.google.com/document/d/1Nm5l4jKBMCyglANAGVqOMs2a4nZxhRIJawBfjvshgm8/edit?usp=meet_tnfm_calendar',
    ai_summary_text: `Resumo do Google Meet (Gemini IA) • Aula 1 (11/08/2026)

Resumo:
O encontro estabeleceu o planejamento pedagógico sobre a história do congregacionalismo e iniciou os estudos sobre o puritanismo e a Reforma Inglesa.

Planejamento e Metodologia:
O professor definiu o cronograma de 16 encontros sobre a história do congregacionalismo e instituiu a obrigatoriedade do uso de câmeras ligadas. A estrutura pedagógica foi dividida entre o contexto do congregacionalismo mundial e o brasileiro.

Contexto da Reforma Inglesa:
A aula abordou o rompimento político de Henrique VIII com Roma e a subsequente via média estabelecida por Elizabeth I. Discutiu-se como a falta de uma reforma teológica completa gerou o surgimento do movimento puritano.

Origens do Puritanismo:
Os alunos analisaram a influência calvinista nos reformadores exilados e as tensões resultantes na Igreja da Inglaterra. O professor recomendou bibliografias essenciais para a compreensão do legado puritano e congregacional.

Bibliografia Recomendada:
- "Quem eram os puritanos" (Erroll Hulse)
- "Santos no Mundo" (Leland Ryken)
- "Os Puritanos: suas origens e sucessores" (D. Martin Lloyd-Jones)
- "A Verdadeira Natureza de uma Igreja Evangélica" (John Owen)

Próximas etapas:
- [Cristiano Sacramento] Enviar slides da apresentação no grupo.
- [Grupo de Alunos] Acessar e preencher a lista de presença.
- [Profº Ary Queiroz Jr] Apresentar detalhes sobre a obra de Packer na próxima aula.`,
    is_live_now: false,
  },
  {
    id: 'aula-20262-2',
    disciplina_id: 'disc-2',
    disciplina_name: '02 - História do Pensamento Cristão II - Hilário Bispo',
    code: 'HIS-102',
    turma_id: 'turma-a',
    turma_idx: 1,
    professor_name: 'Profº Hilário Bispo',
    monitor_name: 'Cristiano',
    day_of_week: 'Terça-feira',
    start_time: '20:35',
    end_time: '22:00',
    title: '02 • História do Pensamento Cristão II — Profº Hilário Bispo',
    description: 'Desenvolvimento do pensamento cristão desde a Reforma Escolástica até a Modernidade.',
    scheduled_at: 'Terça-feira • 20:35 – 22:00',
    google_meet_url: 'https://meet.google.com/cxj-yetd-xpf',
    google_meet_phone: '(BR) +55 11 4933-5763',
    google_meet_pin: '788 555 787#',
    google_drive_url: 'https://drive.google.com/open?id=1iKwbRf-oLpyphrFnM-Km5TWOo2UCU1Me&usp=drive_copy',
    attendance_form_url: 'https://forms.gle/hM2j2fb7DK923wdR7',
    ai_summary_url: 'https://docs.google.com/document/d/1GIGP9tnUWdZs2EzSwFNBf-DtRxzU4a31xYm6hbVZ29U/edit?usp=meet_tnfm_calendar',
    ai_summary_text: `Resumo do Google Meet (Gemini IA) • Aula 1 (11/08/2026)
Disciplina: História do Pensamento Cristão II (HIS-102) • Docente: Profº Hilário Bispo

1. RESUMO EXECUTIVO:
Apresentação da ementa e introdução à transição teológica da Escolástica Medieval para a Reforma Protestante e o Pensamento Moderno.

2. METODOLOGIA E PLANEJAMENTO:
- 16 encontros previstos para o semestre 2026.2 (14 aulas temáticas e 2 avaliações AV1 e AV2).
- Dinâmica com leituras de fontes primárias teológicas e análise contextual dos grandes concílios e controvérsias dogmáticas.

3. TÓPICOS CENTRAIS ABORDADOS:
- A metodologia escolástica (questão disputada e síntese teológica).
- A harmonização entre Fé e Razão no pensamento de Anselmo de Cantuária ("A fé que busca inteligência") e Tomás de Aquino (Suma Teológica).
- A crise do Nominalismo com Guilherme de Ockham e o impacto na teologia tardia medieval.
- O Renascimento Cultural e o princípio humanista "Ad Fontes" (retorno aos idiomas originais hebraico e grego), pavimentando o caminho para a Reforma Protestante.

4. PRÓXIMAS ETAPAS (ACTION ITEMS):
- [Cristiano Sacramento] Disponibilizar o link do formulário de presença no chat.
- [Grupo de Alunos] Realizar a leitura dos textos introdutórios na pasta virtual da disciplina no Google Drive.
- [Profº Hilário Bispo] Aprofundar as raízes teológicas de Martinho Lutero e as 95 Teses no próximo encontro.`,
    is_live_now: false,
  },
  {
    id: 'aula-20262-3',
    disciplina_id: 'disc-3',
    disciplina_name: '03 - Aconselhamento Bíblico II - Uilian Santos',
    code: 'ACO-202',
    turma_id: 'turma-a',
    turma_idx: 1,
    professor_name: 'Profº Uilian Santos',
    monitor_name: 'Rosiane',
    day_of_week: 'Quarta-feira',
    start_time: '19:00',
    end_time: '20:25',
    title: '03 • Aconselhamento Bíblico II — Profº Uilian Santos',
    description: 'Princípios avançados de aconselhamento pastoral, mentoria e apoio emocional nas crises.',
    scheduled_at: 'Quarta-feira • 19:00 – 20:25',
    google_meet_url: 'https://meet.google.com/ifv-zsdd-gjx',
    google_meet_phone: '(BR) +55 11 4949-4189',
    google_meet_pin: '287 717 439#',
    google_drive_url: 'https://drive.google.com/open?id=1BUr0R4pLQjTt01ID8XjYKIBlZhAtaWcx&usp=drive_copy',
    attendance_form_url: 'https://forms.gle/iSLGtjyaTnM9tFGb6',
    ai_summary_url: 'https://docs.google.com/document/d/1y8xcU3pw0f7esxxJTpp13oV2Oc2j9YBy6E85bQqeQyY/edit?usp=meet_tnfm_calendar',
    is_live_now: false,
  },
  {
    id: 'aula-20262-4',
    disciplina_id: 'disc-4',
    disciplina_name: '04 - Direitos Humanos - Cleiton Barbirato',
    code: 'DIR-101',
    turma_id: 'turma-a',
    turma_idx: 1,
    professor_name: 'Profº Cleiton Barbirato',
    monitor_name: 'Cristiano',
    day_of_week: 'Quarta-feira',
    start_time: '20:35',
    end_time: '22:00',
    title: '04 • Direitos Humanos — Profº Cleiton Barbirato',
    description: 'Fundamentos dos Direitos Humanos, cidadania cristã e dignidade da pessoa humana.',
    scheduled_at: 'Quarta-feira • 20:35 – 22:00',
    google_meet_url: 'https://meet.google.com/uva-zmav-rds',
    google_meet_phone: '(BR) +55 51 4560-7412',
    google_meet_pin: '670 189 539#',
    google_drive_url: 'https://drive.google.com/open?id=1fPSmFUBNzrzK--n3NDKOdMR5HWk25AV7&usp=drive_copy',
    attendance_form_url: 'https://forms.gle/QiWRgTit6XjxP9Ci7',
    ai_summary_url: 'https://docs.google.com/document/d/19Y166a7POikgPYX5M3LzqA5MyGYPSydC2hdusz9EY4s/edit?usp=meet_tnfm_calendar',
    is_live_now: false,
  },
  {
    id: 'aula-20262-5',
    disciplina_id: 'disc-5',
    disciplina_name: '05 - Ética Cristã - Karoline Evangelista',
    code: 'ETC-201',
    turma_id: 'turma-a',
    turma_idx: 1,
    professor_name: 'Profª Karoline Evangelista',
    monitor_name: 'Rosiane',
    day_of_week: 'Quinta-feira',
    start_time: '19:00',
    end_time: '20:25',
    title: '05 • Ética Cristã — Profª Karoline Evangelista',
    description: 'Dilemas éticos contemporâneos, bioética, justiça social e princípios bíblicos.',
    scheduled_at: 'Quinta-feira • 19:00 – 20:25',
    google_meet_url: 'https://meet.google.com/ypd-yzwg-nrw',
    google_meet_phone: '(BR) +55 31 3958-9560',
    google_meet_pin: '341 510 949#',
    google_drive_url: 'https://drive.google.com/open?id=1xuOm61ul94H3kdU5psFtbl-I2KZ41QJC&usp=drive_copy',
    attendance_form_url: 'https://forms.gle/Tn3Ln3iS9cbAUEsJ8',
    ai_summary_url: 'https://docs.google.com/document/d/1c0qeSjuKMonuiDT0Fh11fKBu1mvl4KQIGOF57Fwlsso/edit?usp=meet_tnfm_calendar',
    is_live_now: false,
  },
  {
    id: 'aula-20262-6',
    disciplina_id: 'disc-6',
    disciplina_name: '06 - Novo Testamento III - Epístolas Gerais - Marcio Leal',
    code: 'NT-301',
    turma_id: 'turma-a',
    turma_idx: 1,
    professor_name: 'Profº Marcio Leal',
    monitor_name: 'Camila',
    day_of_week: 'Quinta-feira',
    start_time: '20:35',
    end_time: '22:00',
    title: '06 • Novo Testamento III - Epístolas Gerais — Profº Marcio Leal',
    description: 'Exegese e teologia das epístolas universais (Hebreus a Judas).',
    scheduled_at: 'Quinta-feira • 20:35 – 22:00',
    google_meet_url: 'https://meet.google.com/nyn-xjqk-vky',
    google_meet_phone: '(BR) +55 11 4935-0167',
    google_meet_pin: '813 789 014#',
    google_drive_url: 'https://drive.google.com/open?id=1ppsv5caJVbHw-1RwhHu8nxBmqFT9Wm9P&usp=drive_copy',
    attendance_form_url: 'https://forms.gle/SC1mSMSZfDhJPPVE9',
    ai_summary_url: 'https://docs.google.com/document/d/18Rh-IOXaP6TdKBcYF2RrLhjZvqgdFvk4LdlMUIvy4hg/edit?usp=meet_tnfm_calendar',
    is_live_now: false,
  },
  {
    id: 'aula-20262-7',
    disciplina_id: 'disc-7',
    disciplina_name: '07 - Plantação e Revitalização de Igrejas II - Thácyto Lessa',
    code: 'MIS-202',
    turma_id: 'turma-a',
    turma_idx: 1,
    professor_name: 'Profº Thácyto Lessa',
    monitor_name: 'Camila',
    day_of_week: 'Sexta-feira',
    start_time: '19:00',
    end_time: '20:00',
    title: '07 • Plantação e Revitalização de Igrejas II — Profº Thácyto Lessa',
    description: 'Estratégia missionária, plantação de novas comunidades e revitalização de igrejas.',
    scheduled_at: 'Sexta-feira • 19:00 – 20:00',
    google_meet_url: 'https://meet.google.com/jwb-wpvc-pzm',
    google_meet_phone: '(BR) +55 11 4935-2549',
    google_meet_pin: '177 432 157#',
    google_drive_url: 'https://drive.google.com/open?id=1nzXIDnWvvrxSgXQULaSvDGdVr32L_xP8&usp=drive_copy',
    attendance_form_url: 'https://forms.gle/bSqjHe7zsV1EJDDB6',
    ai_summary_url: 'https://docs.google.com/document/d/1eEayAPwfSiaty11o_N1MZBbS2OTXHCrw9CYiVSruLqg/edit?usp=meet_tnfm_calendar',
    is_live_now: false,
  },
  {
    id: 'aula-20262-8',
    disciplina_id: 'disc-8',
    disciplina_name: '08 - TCC I - Gabriela Leal',
    code: 'TCC-101',
    turma_id: 'turma-a',
    turma_idx: 1,
    professor_name: 'Profª Gabriela Leal',
    monitor_name: 'Rosiane',
    day_of_week: 'Sexta-feira',
    start_time: '20:00',
    end_time: '21:00',
    title: '08 • TCC I — Profª Gabriela Leal',
    description: 'Metodologia científica, elaboração de projeto de pesquisa e orientação acadêmica.',
    scheduled_at: 'Sexta-feira • 20:00 – 21:00',
    google_meet_url: 'https://meet.google.com/jnz-hkqd-edc',
    google_meet_phone: '(BR) +55 11 4935-6584',
    google_meet_pin: '568 309 440#',
    google_drive_url: 'https://drive.google.com/open?id=1f-9i-TpqaZhzoLyrxg6flM6CHTsAOWPj&usp=drive_copy',
    attendance_form_url: 'https://forms.gle/vULryGYArnJZgBF28',
    ai_summary_url: 'https://docs.google.com/document/d/1UorXk-6NWK13-h3orl58FYHtnPLLFgJoeKs3y_xUies/edit?usp=meet_tnfm_calendar',
    is_live_now: false,
  },
  {
    id: 'aula-20262-9',
    disciplina_id: 'disc-9',
    disciplina_name: '09 - História da Cultura Afro Brasileira e Indígena - Emerson Silva',
    code: 'AFR-101',
    turma_id: 'turma-a',
    turma_idx: 1,
    professor_name: 'Profº Emerson Silva',
    monitor_name: 'Cristiano',
    day_of_week: 'Sexta-feira',
    start_time: '21:00',
    end_time: '22:00',
    title: '09 • História da Cultura Afro Brasileira e Indígena — Profº Emerson Silva',
    description: 'Estudo da formação étnica brasileira, diversidade cultural e aplicação pastoral.',
    scheduled_at: 'Sexta-feira • 21:00 – 22:00',
    google_meet_url: 'https://meet.google.com/jnz-hkqd-edc',
    google_meet_phone: '(BR) +55 11 4935-6584',
    google_meet_pin: '568 309 440#',
    google_drive_url: 'https://drive.google.com/open?id=13vp8jOcvdtH13O2iauyvsaTCw7DwiPIa&usp=drive_copy',
    attendance_form_url: 'https://forms.gle/vULryGYArnJZgBF28',
    ai_summary_url: 'https://docs.google.com/document/d/1cZjsRZ7Dmw6EVColHpL_zqzZdZunwjbb3vNSgpUL8hg/edit?usp=meet_tnfm_calendar',
    is_live_now: false,
  },

  // ==========================================
  // TURMA B (3º Período - Semanal Noturno)
  // ==========================================
  {
    id: 'aula-turmab-1',
    disciplina_id: 'disc-b-1',
    disciplina_name: 'Introdução ao Novo Testamento',
    code: 'INT-101',
    turma_id: 'turma-b',
    turma_idx: 2,
    professor_name: 'Profº Leonardo Paulino',
    monitor_name: 'Monitoria Turma B',
    day_of_week: 'Terça-feira',
    start_time: '19:00',
    end_time: '20:25',
    title: 'Introdução ao Novo Testamento — Profº Leonardo Paulino',
    description: 'Estudo histórico, eclesiológico e literário dos evangelhos e contexto do Novo Testamento.',
    scheduled_at: 'Terça-feira • 19:00 – 20:25',
    google_meet_url: 'https://meet.google.com/esq-sjmd-sau',
    google_meet_phone: '(BR) +55 11 4933-7995',
    google_meet_pin: '930 167 860#',
    google_meet_tel_url: 'https://tel.meet/esq-sjmd-sau?pin=6781630980308',
    is_live_now: false,
  },
  {
    id: 'aula-turmab-2',
    disciplina_id: 'disc-b-2',
    disciplina_name: 'Hermenêutica Bíblica',
    code: 'HER-101',
    turma_id: 'turma-b',
    turma_idx: 2,
    professor_name: 'Profº David Bezerra',
    monitor_name: 'Monitoria Turma B',
    day_of_week: 'Terça-feira',
    start_time: '20:35',
    end_time: '22:00',
    title: 'Hermenêutica Bíblica — Profº David Bezerra',
    description: 'Princípios e métodos de interpretação das Escrituras, exegese e aplicação teológica.',
    scheduled_at: 'Terça-feira • 20:35 – 22:00',
    google_meet_url: 'https://meet.google.com/vee-maaz-cdn',
    google_meet_phone: '(BR) +55 51 4560-7523',
    google_meet_pin: '800 017 642#',
    google_meet_tel_url: 'https://tel.meet/vee-maaz-cdn?pin=2110831424383',
    is_live_now: false,
  },
  {
    id: 'aula-turmab-3',
    disciplina_id: 'disc-b-3',
    disciplina_name: 'Fundamentos e Prática do Discipulado',
    code: 'DIS-101',
    turma_id: 'turma-b',
    turma_idx: 2,
    professor_name: 'Profº José Milton',
    monitor_name: 'Monitoria Turma B',
    day_of_week: 'Quarta-feira',
    start_time: '19:00',
    end_time: '20:25',
    title: 'Fundamentos e Prática do Discipulado — Profº José Milton',
    description: 'Formação espiritual, acompanhamento pastoral e processos práticos de discipulado na igreja.',
    scheduled_at: 'Quarta-feira • 19:00 – 20:25',
    google_meet_url: 'https://meet.google.com/xrk-hfza-tks',
    google_meet_phone: '(BR) +55 21 4560-7221',
    google_meet_pin: '221 096 667#',
    google_meet_tel_url: 'https://tel.meet/xrk-hfza-tks?pin=7368054294151',
    is_live_now: false,
  },
  {
    id: 'aula-turmab-4',
    disciplina_id: 'disc-b-4',
    disciplina_name: 'Teologia da Missão',
    code: 'MIS-101',
    turma_id: 'turma-b',
    turma_idx: 2,
    professor_name: 'Profº Jefferson Pontes',
    monitor_name: 'Monitoria Turma B',
    day_of_week: 'Quarta-feira',
    start_time: '20:35',
    end_time: '22:00',
    title: 'Teologia da Missão — Profº Jefferson Pontes',
    description: 'Perspectivas bíblicas, históricas e estratégicas da missão da igreja local no mundo.',
    scheduled_at: 'Quarta-feira • 20:35 – 22:00',
    google_meet_url: 'https://meet.google.com/gjg-jrbq-atk',
    google_meet_phone: '(BR) +55 41 4560-9980',
    google_meet_pin: '732 549 857#',
    google_meet_tel_url: 'https://tel.meet/gjg-jrbq-atk?pin=8301681074857',
    is_live_now: false,
  },
  {
    id: 'aula-turmab-5',
    disciplina_id: 'disc-b-5',
    disciplina_name: 'Teologia Sistemática III - Cristologia/Pneumatologia',
    code: 'TS-301',
    turma_id: 'turma-b',
    turma_idx: 2,
    professor_name: 'Profº Marcio Leal',
    monitor_name: 'Monitoria Turma B',
    day_of_week: 'Quinta-feira',
    start_time: '19:00',
    end_time: '20:25',
    title: 'Teologia Sistemática III — Profº Marcio Leal',
    description: 'Doutrina da pessoa e obra do Senhor Jesus Cristo e do Espírito Santo.',
    scheduled_at: 'Quinta-feira • 19:00 – 20:25',
    is_live_now: false,
  },
  {
    id: 'aula-turmab-6',
    disciplina_id: 'disc-b-6',
    disciplina_name: 'Antigo Testamento II - Livros Históricos',
    code: 'AT-201',
    turma_id: 'turma-b',
    turma_idx: 2,
    professor_name: 'Profª Betânia Barbosa',
    monitor_name: 'Monitoria Turma B',
    day_of_week: 'Quinta-feira',
    start_time: '20:35',
    end_time: '22:00',
    title: 'Antigo Testamento II - Livros Históricos — Profª Betânia Barbosa',
    description: 'Análise literária, histórica e teológica dos livros históricos do Antigo Testamento.',
    scheduled_at: 'Quinta-feira • 20:35 – 22:00',
    is_live_now: false,
  },
  {
    id: 'aula-turmab-7',
    disciplina_id: 'disc-b-7',
    disciplina_name: 'Plantação e Revitalização de Igrejas II',
    code: 'MIS-202B',
    turma_id: 'turma-b',
    turma_idx: 2,
    professor_name: 'Profº Thácyto Lessa',
    monitor_name: 'Camila',
    day_of_week: 'Sexta-feira',
    start_time: '19:00',
    end_time: '20:25',
    title: 'Plantação e Revitalização de Igrejas II — Profº Thácyto Lessa',
    description: 'Estratégia missionária, plantação de novas comunidades e revitalização de igrejas.',
    scheduled_at: 'Sexta-feira • 19:00 – 20:25',
    google_meet_url: 'https://meet.google.com/jwb-wpvc-pzm',
    google_meet_phone: '(BR) +55 11 4935-2549',
    google_meet_pin: '177 432 157#',
    is_live_now: false,
  },
  {
    id: 'aula-turmab-8',
    disciplina_id: 'disc-b-8',
    disciplina_name: 'Liderança Cristã',
    code: 'LID-101',
    turma_id: 'turma-b',
    turma_idx: 2,
    professor_name: 'Profº Sandro Cruz',
    monitor_name: 'Monitoria Turma B',
    day_of_week: 'Sexta-feira',
    start_time: '19:00',
    end_time: '20:25',
    title: 'Liderança Cristã — Profº Sandro Cruz',
    description: 'Princípios de liderança bíblica e desenvolvimento ministerial.',
    scheduled_at: 'Sexta-feira • 19:00 – 20:25',
    is_live_now: false,
  },
  {
    id: 'aula-turmab-9',
    disciplina_id: 'disc-b-9',
    disciplina_name: 'Homilética I / Homilética II (Novatos26.2)',
    code: 'HOM-101',
    turma_id: 'turma-b',
    turma_idx: 2,
    professor_name: 'Profº Wellington Estrela',
    monitor_name: 'Módulo Gravado',
    day_of_week: 'Sexta-feira',
    start_time: '19:00',
    end_time: '21:00',
    title: 'Homilética I / Homilética II — Profº Wellington Estrela',
    description: 'Estrutura do sermão e pregação expositiva (Módulo Gravado).',
    scheduled_at: 'Sexta-feira • 19:00 – 21:00',
    google_meet_url: '',
    google_meet_phone: '',
    google_meet_pin: '',
    is_live_now: false,
  },
];

/**
 * Retorna as disciplinas ativas de acordo com a turma (turmaIdx)
 * 0 = Fim de Semana (5º), 1 = Turma A (7º), 2 = Turma B (3º), 3 = Curso Básico
 */
export function getDisciplinasByTurma(turmaIdx: number = 1): Disciplina[] {
  const filtered = mockDisciplinas.filter((d) => d.turma_idx === turmaIdx);
  if (filtered.length > 0) return filtered;
  return mockDisciplinas.filter((d) => (d.turma_idx ?? 1) === 1);
}

/**
 * Retorna as aulas ativas de acordo com a turma (turmaIdx)
 * 0 = Fim de Semana (5º), 1 = Turma A (7º), 2 = Turma B (3º), 3 = Curso Básico
 */
export function getAulasByTurma(turmaIdx: number = 1): Aula[] {
  const filtered = mockAulas.filter((a) => a.turma_idx === turmaIdx);
  if (filtered.length > 0) return filtered;
  return mockAulas.filter((a) => (a.turma_idx ?? 1) === 1);
}

export const mockAvaliacoes: Avaliacao[] = [
  // ==========================================
  // HISTÓRIA DO CONGREGACIONALISMO (disc-1)
  // ==========================================
  {
    id: 'av-his-1',
    disciplina_id: 'disc-1',
    disciplina_name: 'História do Congregacionalismo',
    title: 'AV1: Prova Escrita • Unidade 1 (Congregacionalismo Mundial)',
    description: 'Prova escrita da primeira unidade (origens e história mundial). Composição: 0 a 8 pontos na prova + 1 ponto de frequência ativa + 1 ponto pela leitura ética dos textos.',
    due_date: '2026-10-06T23:59:00',
    google_forms_url: 'https://docs.google.com/forms/d/e/1FAIpQLSe_demo_his_av1/viewform?embedded=true',
    is_legacy: true,
    max_score: 10.0,
  },
  {
    id: 'av-his-2',
    disciplina_id: 'disc-1',
    disciplina_name: 'História do Congregacionalismo',
    title: 'AV2: Prova Escrita • Unidade 2 (Congregacionalismo no Brasil)',
    description: 'Prova escrita final da segunda unidade (vertente brasileira). Composição: 0 a 8 pontos na prova + 1 ponto de frequência ativa + 1 ponto pela leitura ética dos textos.',
    due_date: '2026-12-01T23:59:00',
    google_forms_url: 'https://docs.google.com/forms/d/e/1FAIpQLSe_demo_his_av2/viewform?embedded=true',
    is_legacy: true,
    max_score: 10.0,
  },

  // ==========================================
  // HISTÓRIA DO PENSAMENTO CRISTÃO II (disc-2)
  // ==========================================
  {
    id: 'av-hpc-1',
    disciplina_id: 'disc-2',
    disciplina_name: 'História do Pensamento Cristão II',
    title: 'AV1: Trabalho Acadêmico ABNT • Iluminismo & Modernidade',
    description: 'Pesquisa acadêmica sob normas ABNT abordando o conflito entre razão e revelação, impactos no cristianismo, liberalismo teológico e reações contemporâneas. Individual ou grupos de até 3 pessoas.',
    due_date: '2026-10-06T23:59:00',
    is_legacy: false,
    max_score: 10.0,
  },
  {
    id: 'av-hpc-2',
    disciplina_id: 'disc-2',
    disciplina_name: 'História do Pensamento Cristão II',
    title: 'AV2: Prova Objetiva (10 Questões) • Google Forms',
    description: 'Prova objetiva contendo 10 questões de múltipla escolha via Google Forms, com correção e resultado instantâneo.',
    due_date: '2026-12-01T23:59:00',
    google_forms_url: 'https://docs.google.com/forms/d/e/1FAIpQLSe_demo_hpc_av2/viewform?embedded=true',
    is_legacy: true,
    max_score: 10.0,
  },
  {
    id: 'av-hpc-3',
    disciplina_id: 'disc-2',
    disciplina_name: 'História do Pensamento Cristão II',
    title: 'AV3 (Recuperação): Exame Oral Temático',
    description: 'Prova oral de tema específico conduzida pelo Profº Hilário Bispo (aplicável exclusivamente em casos de recuperação).',
    due_date: '2026-12-08T23:59:00',
    is_legacy: false,
    max_score: 10.0,
  },

  // ==========================================
  // ACONSELHAMENTO BÍBLICO II (disc-3)
  // ==========================================
  {
    id: 'av-aco-1',
    disciplina_id: 'disc-3',
    disciplina_name: 'Aconselhamento Bíblico II',
    title: 'AV1: Prova Objetiva • Google Forms (Conteúdo dos Slides)',
    description: 'Prova 100% objetiva disponibilizada via Google Forms. Sem exigência de trabalhos escritos; questões focadas estritamente nos slides das aulas. Correção e nota automáticas.',
    due_date: '2026-10-07T23:59:00',
    google_forms_url: 'https://docs.google.com/forms/d/e/1FAIpQLSe_demo_aco_av1/viewform?embedded=true',
    is_legacy: true,
    max_score: 10.0,
  },
  {
    id: 'av-aco-2',
    disciplina_id: 'disc-3',
    disciplina_name: 'Aconselhamento Bíblico II',
    title: 'AV2: Prova Objetiva Final • Google Forms (Conteúdo dos Slides)',
    description: 'Segunda prova objetiva do semestre via Google Forms. Questões focadas nos slides de aula. Correção automática.',
    due_date: '2026-12-02T23:59:00',
    google_forms_url: 'https://docs.google.com/forms/d/e/1FAIpQLSe_demo_aco_av2/viewform?embedded=true',
    is_legacy: true,
    max_score: 10.0,
  },

  // ==========================================
  // DIREITOS HUMANOS (disc-4)
  // ==========================================
  {
    id: 'av-dir-1',
    disciplina_id: 'disc-4',
    disciplina_name: 'Direitos Humanos',
    title: 'V1: Prova Objetiva (Peso 8) + Produção Textual Individual (Peso 2)',
    description: 'Etapa avaliativa V1 composta por: Prova objetiva Google Forms sem consulta (Peso 8,0) + Trabalho de pesquisa escrito individual enviado por e-mail/WhatsApp (Peso 2,0). Média >= 7,0 para aprovação.',
    due_date: '2026-10-07T23:59:00',
    google_forms_url: 'https://docs.google.com/forms/d/e/1FAIpQLSe_demo_dir_v1/viewform?embedded=true',
    is_legacy: true,
    max_score: 10.0,
  },
  {
    id: 'av-dir-2',
    disciplina_id: 'disc-4',
    disciplina_name: 'Direitos Humanos',
    title: 'V2: Prova Objetiva (Peso 8) + Produção Textual Individual (Peso 2)',
    description: 'Etapa avaliativa V2 composta por: Prova objetiva Google Forms sem consulta (Peso 8,0) + Trabalho de pesquisa escrito individual (Peso 2,0). Média final ponderada >= 7,0.',
    due_date: '2026-12-02T23:59:00',
    google_forms_url: 'https://docs.google.com/forms/d/e/1FAIpQLSe_demo_dir_v2/viewform?embedded=true',
    is_legacy: true,
    max_score: 10.0,
  },

  // ==========================================
  // ÉTICA CRISTÃ (disc-5)
  // ==========================================
  {
    id: 'av-eti-1',
    disciplina_id: 'disc-5',
    disciplina_name: 'Ética Cristã',
    title: 'Avaliação Unificada V1 & V2: Seminário em Grupo • Os Dez Mandamentos',
    description: 'Apresentação em grupo (3 a 4 alunos) com base no Catecismo Maior de Westminster e livro de Norman Geisler. Período: 22/10 a 19/11. Duração: 30 min (10 min por orador no cronômetro). Nota individual avaliando slides e oratória.',
    due_date: '2026-11-19T23:59:00',
    is_legacy: false,
    max_score: 10.0,
  },

  // ==========================================
  // NOVO TESTAMENTO III - EPÍSTOLAS GERAIS (disc-6)
  // ==========================================
  {
    id: 'av-nt-1',
    disciplina_id: 'disc-6',
    disciplina_name: 'Novo Testamento III - Epístolas Gerais',
    title: 'AV Semestral: Bateria de 150 Questões Discursivas & Orais (Google Forms)',
    description: 'Carga massiva de 150 questões aplicadas via Google Forms baseadas no livro-texto de Carson/Moo/Morris e nas anotações detalhadas dos slides da aula.',
    due_date: '2026-11-26T23:59:00',
    google_forms_url: 'https://docs.google.com/forms/d/e/1FAIpQLSe_demo_nt_150q/viewform?embedded=true',
    is_legacy: true,
    max_score: 10.0,
  },

  // ==========================================
  // PLANTAÇÃO E REVITALIZAÇÃO DE IGREJAS II (disc-7)
  // ==========================================
  {
    id: 'av-pla-1',
    disciplina_id: 'disc-7',
    disciplina_name: 'Plantação e Revitalização de Igrejas II',
    title: 'AV1: Resumo de 12 Páginas • Livro "A Treliça e a Videira"',
    description: 'Elaboração de resumo capítulo por capítulo do livro "A Treliça e a Videira" (1 página por capítulo, total de 12 folhas). Envio para thacyto@gmail.com impreterivelmente até 27/11/2026.',
    due_date: '2026-11-27T23:59:00',
    is_legacy: false,
    max_score: 10.0,
  },
  {
    id: 'av-pla-2',
    disciplina_id: 'disc-7',
    disciplina_name: 'Plantação e Revitalização de Igrejas II',
    title: 'AV2: Prova por Link com Consulta aos Slides e Anotações',
    description: 'Prova por link individual de formulário aplicada em 27/11/2026. A consulta às anotações pessoais e slides do professor será 100% permitida.',
    due_date: '2026-11-27T23:59:00',
    google_forms_url: 'https://docs.google.com/forms/d/e/1FAIpQLSe_demo_pla_av2/viewform?embedded=true',
    is_legacy: true,
    max_score: 10.0,
  },

  // ==========================================
  // TRABALHO DE CONCLUSÃO DE CURSO I - TCC I (disc-8)
  // ==========================================
  {
    id: 'av-tcc-1',
    disciplina_id: 'disc-8',
    disciplina_name: 'TCC I',
    title: 'Etapa 1: Entrega do Projeto de Pesquisa Estruturado ABNT',
    description: 'Prazo limite de 2 semanas (04/09/2026). Estrutura obrigatória: Capa, Sumário, Objetivos (geral + 2-3 específicos no infinitivo), Justificativa, Referencial Teórico, Cronograma em tabela. Linguagem científica impessoal.',
    due_date: '2026-09-04T23:59:00',
    is_legacy: false,
    max_score: 10.0,
  },
  {
    id: 'av-tcc-2',
    disciplina_id: 'disc-8',
    disciplina_name: 'TCC I',
    title: 'Etapa Final: Artigo Científico e Avaliação Contínua',
    description: 'Sem provas tradicionais. Avaliação contínua do progresso com orientador e entrega do artigo científico completo formatado conforme as normas da ABNT.',
    due_date: '2026-12-04T23:59:00',
    is_legacy: false,
    max_score: 10.0,
  },
];

export const mockMateriais: Material[] = [
  {
    id: 'mat-2026-1',
    disciplina_id: 'disc-1',
    disciplina_name: 'História do Congregacionalismo',
    title: 'História do Congregacionalismo - Prof Ary Junior',
    google_drive_url: 'https://drive.google.com/open?id=19Y8Nv2Yvx1V-m4E5y5fUWOo5e8DZzeji&usp=drive_copy',
    is_native_upload: false,
    created_at: '2026-07-22',
  },
  {
    id: 'mat-2026-2',
    disciplina_id: 'disc-2',
    disciplina_name: 'História do Pensamento Cristão II',
    title: 'História do Pensamento Cristão II - Prof Hilário Bispo',
    google_drive_url: 'https://drive.google.com/open?id=1iKwbRf-oLpyphrFnM-Km5TWOo2UCU1Me&usp=drive_copy',
    is_native_upload: false,
    created_at: '2026-07-22',
  },
  {
    id: 'mat-2026-3',
    disciplina_id: 'disc-3',
    disciplina_name: 'Aconselhamento Bíblico II',
    title: 'Aconselhamento Bíblico II - Prof Uilian Santos',
    google_drive_url: 'https://drive.google.com/open?id=1BUr0R4pLQjTt01ID8XjYKIBlZhAtaWcx&usp=drive_copy',
    is_native_upload: false,
    created_at: '2026-07-22',
  },
  {
    id: 'mat-2026-4',
    disciplina_id: 'disc-4',
    disciplina_name: 'Direitos Humanos',
    title: 'Direitos Humanos - Prof Cleiton Barbirato',
    google_drive_url: 'https://drive.google.com/open?id=1fPSmFUBNzrzK--n3NDKOdMR5HWk25AV7&usp=drive_copy',
    is_native_upload: false,
    created_at: '2026-07-22',
  },
  {
    id: 'mat-2026-5',
    disciplina_id: 'disc-5',
    disciplina_name: 'Ética Cristã',
    title: 'Ética Cristã - Profa Karoline Evangelista',
    google_drive_url: 'https://drive.google.com/open?id=1xuOm61ul94H3kdU5psFtbl-I2KZ41QJC&usp=drive_copy',
    is_native_upload: false,
    created_at: '2026-07-22',
  },
  {
    id: 'mat-2026-6',
    disciplina_id: 'disc-6',
    disciplina_name: 'Novo Testamento III - Epístolas Gerais',
    title: 'Novo Testamento III - Epístolas Gerais - Prof Márcio Leal',
    google_drive_url: 'https://drive.google.com/open?id=1ppsv5caJVbHw-1RwhHu8nxBmqFT9Wm9P&usp=drive_copy',
    is_native_upload: false,
    created_at: '2026-07-22',
  },
  {
    id: 'mat-2026-7',
    disciplina_id: 'disc-7',
    disciplina_name: 'Plantação e Revitalização de Igrejas II',
    title: 'Plantação e Revitalização de Igrejas - II - Prof Thácyto Lessa',
    google_drive_url: 'https://drive.google.com/open?id=1nzXIDnWvvrxSgXQULaSvDGdVr32L_xP8&usp=drive_copy',
    is_native_upload: false,
    created_at: '2026-07-22',
  },
  {
    id: 'mat-2026-8',
    disciplina_id: 'disc-8',
    disciplina_name: 'TCC I',
    title: 'Trabalho de Conclusão de Curso - I - Profa Gabriela Leal',
    google_drive_url: 'https://drive.google.com/open?id=1f-9i-TpqaZhzoLyrxg6flM6CHTsAOWPj&usp=drive_copy',
    is_native_upload: false,
    created_at: '2026-07-22',
  },
  {
    id: 'mat-2026-9',
    disciplina_id: 'disc-9',
    disciplina_name: 'História e Cultura Afro Brasileira e Indígena',
    title: 'História e Cultura Afro Brasileira e Indígena',
    google_drive_url: 'https://drive.google.com/open?id=13vp8jOcvdtH13O2iauyvsaTCw7DwiPIa&usp=drive_copy',
    is_native_upload: false,
    created_at: '2026-07-22',
  },
];
